In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
import dask.array as da
import os
from pycontrails.physics import geo, thermo, units, constants

In [2]:
job_id = 966852

fl = pd.read_pickle("outputs/" + repr(job_id) + "/fl_" + repr(job_id) + ".pkl")

fl

,longitude,latitude,altitude,time,air_temperature,specific_humidity,true_airspeed,flight_id,aircraft_mass,engine_efficiency,...,NO,NO2,CO,HCHO,CH3CHO,C2H4,C3H6,C2H2,BENZENE,waypoint
0,0.125000,0.100000,12500.0,2022-01-20 13:00:00,212.263516,0.000219,100.230014,0.0,62518.613860,0.099880,...,2.048795,0.107831,0.062205,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,0
1,0.201229,0.176736,12500.0,2022-01-20 13:02:00,212.259403,0.000218,100.229809,0.0,62376.929746,0.099880,...,2.049022,0.107843,0.062205,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,1
2,0.277457,0.253473,12500.0,2022-01-20 13:04:00,212.255158,0.000218,100.229514,0.0,62235.235247,0.099881,...,2.049256,0.107856,0.062206,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,2
3,0.353686,0.330209,12500.0,2022-01-20 13:06:00,212.250782,0.000218,100.229130,0.0,62093.530027,0.099881,...,2.049498,0.107868,0.062206,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,3
4,0.429914,0.406945,12500.0,2022-01-20 13:08:00,212.246275,0.000217,100.228656,0.0,61951.813748,0.099881,...,2.049747,0.107881,0.062207,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,4
5,0.506143,0.483682,12500.0,2022-01-20 13:10:00,212.241637,0.000217,100.228093,0.0,61810.086073,0.099882,...,2.050005,0.107895,0.062208,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,5
6,0.582371,0.560418,12500.0,2022-01-20 13:12:00,212.236868,0.000217,100.227441,0.0,61668.346665,0.099882,...,2.050270,0.107909,0.062208,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,6
7,0.658600,0.637154,12500.0,2022-01-20 13:14:00,212.231968,0.000216,100.229528,0.0,61526.595186,0.099884,...,2.050540,0.107923,0.062209,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,7
8,0.734838,0.713886,12500.0,2022-01-20 13:16:00,212.226937,0.000216,100.231527,0.0,61384.831486,0.099885,...,2.050818,0.107938,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,8
9,0.811084,0.790613,12500.0,2022-01-20 13:18:00,212.221775,0.000215,100.230606,0.0,61243.055229,0.099885,...,2.051106,0.107953,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,9
10,0.887331,0.867340,12500.0,2022-01-20 13:20:00,212.216482,0.000215,100.230606,0.0,61101.265886,0.099885,...,2.051106,0.107953,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,10

In [8]:
outputs_dir = "/user/home/kt16229/work/pycontrails_kt/pycontrails/models/gpat/outputs/"

jobs = []

for job_id in os.listdir(outputs_dir):
    job_dir = os.path.join(outputs_dir, job_id)
    if os.path.isdir(job_dir):
        # Check if the expected files exist in the subdirectory
        expected_files = [
            f"params_{job_id}.pkl",
            f"fl_{job_id}.pkl",
            f"pl_{job_id}.pkl",
            f"chem_{job_id}.nc"
        ]
        if all(os.path.isfile(os.path.join(job_dir, file)) for file in expected_files):
            
            params = pd.read_pickle("outputs/" + job_id + "/params_" + job_id + ".pkl")

            # Flatten the dictionary
            data_dict = {f"{inner_key}": inner_value 
                            for outer_key, inner_dict in params.items() 
                            for inner_key, inner_value in inner_dict.items()}

            jobs.append(data_dict)

jobs
jobs_df = pd.DataFrame(jobs)
jobs_df

,t0_fl,rt_fl,ts_fl,ac_type,fl0_speed,fl0_heading,fl0_coords0,sep_dist,n_ac,dt_integration,...,lat_bounds,lon_bounds,alt_bounds,hres_sim,vres_sim,eastward_wind,northward_wind,lagrangian_tendency_of_air_pressure,species_out,job_id
0,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(0.1, 0.125, 12500)","(5000, 2000, 0)",1,0 days 00:02:00,...,"(0.0, 1.0)","(0.0, 1.0)","(12000, 13000)",0.05,500,0.0,0.0,0.0,"[3, 4, 5, 6, 8, 9]",966852
1,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(0.1, 0.125, 12500)","(5000, 2000, 0)",2,0 days 00:02:00,...,"(0.0, 1.0)","(0.0, 1.0)","(12000, 13000)",0.05,500,0.0,0.0,0.0,"[3, 4, 5, 6, 8, 9]",409717

In [ ]:
fl = pd.read_pickle("outputs/" + repr(job_id) + "/fl_" + repr(job_id) + ".pkl")
fl

In [ ]:
pl = pd.read_pickle("outputs/" + repr(job_id) + "/pl_" + repr(job_id) + ".pkl")
pl

In [ ]:
chem = xr.open_dataset("outputs/" + repr(job_id) +"/chem_" + repr(job_id) + ".nc")
# chem["emi"].sel(emi_species="NO", time=pl["time"][0]).sel(level=178.6, method="nearest").plot()

chem

In [ ]:
fig1, ax1 = plt.subplots()
ax1.set_xticks(np.arange(chem["longitude"][0], chem["longitude"][-1], 0.05))
ax1.set_yticks(np.arange(chem["latitude"][0], chem["latitude"][-1], 0.05))


ts = 26

# Plot the heatmap
heatmap_data = (
    chem.Y.sel(species_out=0, time=pl.time[ts])
    .sel(level=178.6, method="nearest")
    .transpose("latitude", "longitude")
)
heatmap_data.plot(ax=ax1, cmap="summer")  # You can choose a colormap of your preference


# scat_fl = ax1.scatter(
#     fl["longitude"].loc[fl["time"] == pl["time"][ts]],
#     fl["latitude"].loc[fl["time"] == pl["time"][ts]],
#     s=5,
#     c="red",
#     label="Flight path",
# )

scat_pl = ax1.scatter(
    pl["longitude"].loc[pl["time"] == pl["time"][ts]],
    pl["latitude"].loc[pl["time"] == pl["time"][ts]],
    s=10e-2 * pl["width"].loc[pl["time"] == pl["time"][ts]],
    c="blue",
    label="Plume evolution",
)

ax1.legend(loc="upper left")
ax1.set_xlim([params["sim_params"]["lon_bounds"][0], params["sim_params"]["lon_bounds"][1]])
ax1.set_ylim([params["sim_params"]["lat_bounds"][0], params["sim_params"]["lat_bounds"][1]])
# plt.grid()
plt.show()

In [ ]:

"""Check if mass is conserved in the box model."""

mm = [30.01, 46.01, 28.01, 30.03, 44.05, 28.05, 42.08, 26.04, 78.11]  # g/mol
NA = 6.022e23  # Avogadro's number

total_vector_mass = 0
total_grid_mass = 0
for ts, time in enumerate(fl["time"][:-1]):
    print(time)
    # grab vector data
    for s, emi_species in enumerate(["NO"]):# self.boxm_ds_unstacked["emi_species"].data):
        
        vector_mass = fl[emi_species][ts]
    
        total_vector_mass += vector_mass

        # grab plume mass from grid data
        grid_concs = chem["emi"].sel(emi_species=emi_species, time=time).sel(level=178.6, method="nearest")

        if (grid_concs == 0).all():
            print("All values in grid_concs are zeros. Skipping processing.")
        else:
            grid_concs_over_zero = grid_concs.where(grid_concs > 0, drop=True)

            grid_mass = grid_concs_over_zero \
                * chem["M"].sel(time=time).sel(level=178.6, method="nearest") \
                * 1e-9 \
                * (mm[s] / NA) \
                * params["sim_params"]["vres_sim"] \
                * units.latitude_distance_to_m(params["sim_params"]["hres_sim"]) \
                * units.longitude_distance_to_m(params["sim_params"]["hres_sim"], (params["sim_params"]["lat_bounds"][0] + params["sim_params"]["lat_bounds"][1]) / 2) \
                * 1E+03 # convert to kg/m^3
                

            total_grid_mass = grid_mass.sum().values
            #total_grid_mass += grid_mass_sum
    
    print(total_vector_mass, total_grid_mass)