In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
import os
import re
from pycontrails.core import GeoVectorDataset
from pycontrails.models.gpat.gpat import create_jobs_df, filter_jobs_df, load_fl_df, load_pl_df, load_chem_ds, plot_heatmap, anim_chem, mc_test, boxm_test

In [2]:
outputs_dir = f"{os.getcwd()}/outputs/"

In [7]:
# Filter criteria
criteria = {
        # "n_ac": 3,
        # "rt_fl": (pd.Timedelta(minutes=30), pd.Timedelta(hours=2)),
        # "date_created": (pd.Timestamp("2024-11-16"), pd.Timestamp("2024-11-17")),
        "job_id": 'sensitivity'
    }

In [8]:
jobs_df = create_jobs_df(outputs_dir)

jobs_df

# jobs_df.set_index('job_id', inplace=True)

# # Define the function to modify job_id
# def modify_job_id(job_id):
#     if 'id_vs_plume_NA__' in job_id:
#         return job_id.replace('id_vs_plume_NA__', 'id_vs_plume_NA_')
#     return job_id

# # Reset the index to modify job_id
# jobs_df.reset_index(inplace=True)

# # Apply the function to the job_id column
# jobs_df['job_id'] = jobs_df['job_id'].apply(modify_job_id)

# # Set job_id back as the index
# jobs_df.set_index('job_id', inplace=True)

# # Iterate over the rows and save each to a separate file
# for job_id, row in jobs_df.iterrows():
      
#     # Define the file path
#     file_path = f'/user/work/kt16229/pycontrails_kt/pycontrails/models/gpat/outputs/{job_id}/params_{job_id}.pkl'
    
#     # Save the row to a pickle file
#     row.to_frame().T.to_pickle(file_path)

# print("Files saved successfully.")

,t0_fl,rt_fl,ts_fl,ac_type,fl0_speed,fl0_heading,fl0_coords0,sep_dist,n_ac,dt_integration,...,traj_gen_proc,gen_met_proc,bg_chem_proc,ac_perf_proc,emissions_proc,sim_plumes_proc,plume_to_grid_proc,run_cc_proc,run_boxm_proc,gen_outputs_proc
job_id,,,,,,,,,,,,,,,,,,,,,
sensitivity_NA_2_1000_0_2_0.01_0.05,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(1000, 0, 0)",2,0 days 00:02:00,...,0.012016,5.372012,0.295543,0.045942,0.085317,1.275117,647.217342,0.000001,8.441803,0
boxm_v_EU_20_5,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(0, 0, 0)",0,0 days 00:02:00,...,0.000011,5.432010,0.292648,0.000003,0.000001,0.000001,5.609954,0.000001,8.739993,0
boxm_v_SA_20_5,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(0, 0, 0)",0,0 days 00:02:00,...,0.000005,5.199766,0.287123,0.000003,0.000002,0.000001,5.610945,0.000002,8.667377,0
boxm_v_US_20_5,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(0, 0, 0)",0,0 days 00:02:00,...,0.000014,5.074076,0.342533,0.000003,0.000002,0.000002,5.384802,0.000002,9.369998,0
boxm_v_SEA_20_5,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(0, 0, 0)",0,0 days 00:02:00,...,0.000005,5.385054,0.288502,0.000003,0.000001,0.000004,5.600920,0.000001,8.681283,0
sensitivity_NA_1_1000_0_2_0.01_0.05,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(1000, 0, 0)",1,0 days 00:02:00,...,0.015442,5.389322,0.290681,0.029126,0.064892,1.043510,332.664212,0.000001,8.481372,0
boxm_v_NA_20_5,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(0, 0, 0)",0,0 days 00:02:00,...,0.000011,5.464715,0.312048,0.000004,0.000002,0.000002,6.194720,0.000002,9.695035,0
sensitivity_NA_5_1000_0_2_0.01_0.05,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(1000, 0, 0)",5,0 days 00:02:00,...,0.012595,5.368205,0.286664,0.096568,0.175723,2.004333,1601.057121,0.000002,8.463704,0

In [9]:
filtered_df = filter_jobs_df(jobs_df, criteria)

job_ids = filtered_df.index.values
 
filtered_df

,t0_fl,rt_fl,ts_fl,ac_type,fl0_speed,fl0_heading,fl0_coords0,sep_dist,n_ac,dt_integration,...,traj_gen_proc,gen_met_proc,bg_chem_proc,ac_perf_proc,emissions_proc,sim_plumes_proc,plume_to_grid_proc,run_cc_proc,run_boxm_proc,gen_outputs_proc
job_id,,,,,,,,,,,,,,,,,,,,,
sensitivity_NA_2_1000_0_2_0.01_0.05,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(1000, 0, 0)",2,0 days 00:02:00,...,0.012016,5.372012,0.295543,0.045942,0.085317,1.275117,647.217342,0.000001,8.441803,0
sensitivity_NA_1_1000_0_2_0.01_0.05,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(1000, 0, 0)",1,0 days 00:02:00,...,0.015442,5.389322,0.290681,0.029126,0.064892,1.043510,332.664212,0.000001,8.481372,0
sensitivity_NA_5_1000_0_2_0.01_0.05,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(47.1, -32.9, 12500)","(1000, 0, 0)",5,0 days 00:02:00,...,0.012595,5.368205,0.286664,0.096568,0.175723,2.004333,1601.057121,0.000002,8.463704,0

In [10]:
fl_df = load_fl_df(job_ids, outputs_dir)

fl_df

plume_time_data = GeoVectorDataset(data=fl_df.loc[fl_df["time"] == fl_df["time"].min()])

In [11]:
pl_df = load_pl_df(job_ids, outputs_dir)
pl_df.columns

pl_df

,flight_id,waypoint,fuel_flow,fuel_burn,true_airspeed,CO2,H2O,SO2,NO,NO2,...,longitude,latitude,level,width,heading,sigma_yy,sigma_zz,sin_a,cos_a,altitude
job_id,,,,,,,,,,,,,,,,,,,,,
sensitivity_NA_2_1000_0_2_0.01_0.05,0.0,0,1.039642,124.757011,100.099398,394.232154,153.451123,0.104796,1.712263,0.090119,...,-32.900000,47.100000,178.645172,81.026358,NaN,8.206588e+02,433.664232,NaN,NaN,12500.0
sensitivity_NA_2_1000_0_2_0.01_0.05,1.0,0,1.039631,124.755700,100.093336,394.228012,153.449511,0.104795,1.712236,0.090118,...,-32.890684,47.106360,178.645172,81.026206,NaN,8.206558e+02,433.657838,NaN,NaN,12500.0
sensitivity_NA_2_1000_0_2_0.01_0.05,0.0,0,1.039642,124.757011,100.099398,394.232154,153.451123,0.104796,1.712263,0.090119,...,-32.900000,47.100000,178.645172,143.604196,44.595919,2.577771e+03,554.828465,0.702102,0.712076,12500.0
sensitivity_NA_2_1000_0_2_0.01_0.05,0.0,1,1.039507,124.740886,100.027041,394.181199,153.431289,0.104782,1.711931,0.090102,...,-32.787015,47.175907,178.645172,81.024516,44.595919,8.206215e+02,433.586506,0.702102,0.712076,12500.0
sensitivity_NA_2_1000_0_2_0.01_0.05,1.0,0,1.039631,124.755700,100.093336,394.228012,153.449511,0.104795,1.712236,0.090118,...,-32.890684,47.106360,178.645172,143.603512,44.599371,2.577746e+03,554.815676,0.702145,0.712034,12500.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
sensitivity_NA_5_1000_0_2_0.01_0.05,0.0,7,1.038809,124.657109,99.664701,393.916464,153.328244,0.104712,1.710212,0.090011,...,-32.109103,47.631346,178.645172,10630.543778,NaN,1.412606e+07,7549.621023,NaN,NaN,12500.0
sensitivity_NA_5_1000_0_2_0.01_0.05,1.0,7,1.038797,124.655694,99.658621,393.911992,153.326503,0.104711,1.710183,0.090010,...,-32.099787,47.637706,178.645172,10630.292721,NaN,1.412539e+07,7549.234906,NaN,NaN,12500.0
sensitivity_NA_5_1000_0_2_0.01_0.05,2.0,7,1.038786,124.654277,99.652541,393.907514,153.324760,0.104710,1.710154,0.090008,...,-32.090471,47.644067,178.645172,10630.041607,NaN,1.412472e+07,7548.848711,NaN,NaN,12500.0
sensitivity_NA_5_1000_0_2_0.01_0.05,3.0,7,1.038774,124.652858,99.646461,393.903031,153.323015,0.104708,1.710125,0.090007,...,-32.081153,47.650427,178.645172,10629.790436,NaN,1.412406e+07,7548.462436,NaN,NaN,12500.0
sensitivity_NA_5_1000_0_2_0.01_0.05,4.0,7,1.038762,124.651437,99.640381,393.898542,153.321268,0.104707,1.710096,0.090005,...,-32.071834,47.656787,178.645172,10629.539208,NaN,1.412339e+07,7548.076083,NaN,NaN,12500.0

In [ ]:
chem_ds = load_chem_ds(job_ids, outputs_dir)

chem_ds = chem_ds.assign_coords(species_out=chem_ds.attrs["species_out"])

chem_ds_stacked = chem_ds.stack(
            {"cell": ["level", "longitude", "latitude"]}
        )
chem_ds_stacked = chem_ds_stacked.reset_index("cell")

In [ ]:

max_emi_cell = chem_ds_stacked["emi"].mean(dim="time").argmax()#.item()
print(max_emi_cell)
# find cell that has max emissions averaged over time in it
cell_chem_ds = chem_ds_stacked.sel(job_id=job_ids[0], cell=max_emi_cell)
cell_chem_ds
# Select the emissions for the specified species
emi_data = cell_chem_ds["emi"].sel(emi_species="NO")
chem_data = cell_chem_ds["Y"].sel(species_out="NO")
emi_data.plot()
chem_data.plot()

# # # Convert time and emi data to pandas Series
# # ts = 0
# # time_series = pd.Series(emi_data["time"].values)
# # emi_series = pd.Series(emi_data.values)

# # # Print time and emi values side by side
# # for time, emi in zip(time_series, emi_series):
# #     ts += 1
# #     print(f"TS: {ts}, Time: {time}, EMI: {emi}")

# for s, species in enumerate(chem_ds["species"].values):
#     print(chem_ds["bg_chem"].isel(level=1,latitude=0,longitude=0, species=s).values)

In [ ]:
#anim_chem(job_ids[0], jobs_df, fl_df, pl_df, chem_ds, var1="Y", var2="O3", level=178.6, resample_freq="2min")

In [ ]:
# vecmass, gridmass, mc = mc_test(job_ids[0], jobs_df, fl_df, pl_df, chem_ds)
# mc

In [ ]:
path = '/user/work/kt16229/pycontrails_kt/pycontrails/models/gpat/'

cell_chem_ds = boxm_test(path, job_ids[0], 0, chem_ds)

# dj_data = cell_chem_ds["DJ"].sel(photol_coeffs=3)
# dj_orig_data = cell_chem_ds["DJ_orig"].sel(photol_coeffs=3)
# dj_data.plot()
# dj_orig_data.plot()

chem_data = cell_chem_ds["Y"].sel(species_out="NO")
chem_orig_data = cell_chem_ds["Y_orig"].sel(species_out="NO")
chem_data.plot()
chem_orig_data.plot()