In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
import dask.array as da
import os
from pycontrails.models.gpat.gpat import GPAT, create_jobs_df, filter_jobs_df, load_fl_df, load_pl_df, load_chem_ds, mc_test, boxm_test

In [2]:
outputs_dir = f"{os.getcwd()}/outputs/"

outputs_dir

'/home/ktait98/pycontrails_kt/pycontrails/models/gpat/outputs/'

In [3]:
# Filter criteria
criteria = {
        "n_ac": 1,
        "rt_fl": (pd.Timedelta(minutes=30), pd.Timedelta(hours=2)),
    }

In [4]:
jobs_df = create_jobs_df(outputs_dir)

jobs_df

,t0_fl,rt_fl,ts_fl,ac_type,fl0_speed,fl0_heading,fl0_coords0,sep_dist,n_ac,dt_integration,...,alt_bounds,hres_sim,vres_sim,eastward_wind,northward_wind,lagrangian_tendency_of_air_pressure,species_in,species_out,date_created,species_out_num
job_id,,,,,,,,,,,,,,,,,,,,,
403478,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(0.1, 0.125, 12500)","(5000, 2000, 0)",1,0 days 00:02:00,...,"(12000, 13000)",0.05,500,0.0,0.0,0.0,"[NO, NO2, CO]","[O3, NO2, NO, NO3, HNO3, PAN, HONO, HO2, OH, H...",2024-11-06 17:53:58.975393,"[6, 4, 8, 5, 14, 198, 13, 9, 3, 12, 11, 39, 21]"

In [5]:
filtered_df = filter_jobs_df(jobs_df, criteria)

job_ids = filtered_df.index.values

job_ids

array(['403478'], dtype=object)

In [6]:
fl_df = load_fl_df(job_ids, outputs_dir)

fl_df

,longitude,latitude,altitude,time,air_temperature,specific_humidity,true_airspeed,flight_id,aircraft_mass,engine_efficiency,...,NO,NO2,CO,HCHO,CH3CHO,C2H4,C3H6,C2H2,BENZENE,waypoint
job_id,,,,,,,,,,,,,,,,,,,,,
403478,0.125000,0.100000,12500.0,2022-01-20 13:00:00,212.263516,0.000219,100.230014,0.0,62518.613860,0.099880,...,2.048795,0.107831,0.062205,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,0
403478,0.201229,0.176736,12500.0,2022-01-20 13:02:00,212.259403,0.000218,100.229809,0.0,62376.929746,0.099880,...,2.049022,0.107843,0.062205,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,1
403478,0.277457,0.253473,12500.0,2022-01-20 13:04:00,212.255158,0.000218,100.229514,0.0,62235.235247,0.099881,...,2.049256,0.107856,0.062206,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,2
403478,0.353686,0.330209,12500.0,2022-01-20 13:06:00,212.250782,0.000218,100.229130,0.0,62093.530027,0.099881,...,2.049498,0.107868,0.062206,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,3
403478,0.429914,0.406945,12500.0,2022-01-20 13:08:00,212.246275,0.000217,100.228656,0.0,61951.813748,0.099881,...,2.049747,0.107881,0.062207,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,4
403478,0.506143,0.483682,12500.0,2022-01-20 13:10:00,212.241637,0.000217,100.228093,0.0,61810.086073,0.099882,...,2.050005,0.107895,0.062208,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,5
403478,0.582371,0.560418,12500.0,2022-01-20 13:12:00,212.236868,0.000217,100.227441,0.0,61668.346665,0.099882,...,2.050270,0.107909,0.062208,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,6
403478,0.658600,0.637154,12500.0,2022-01-20 13:14:00,212.231968,0.000216,100.229528,0.0,61526.595186,0.099884,...,2.050540,0.107923,0.062209,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,7
403478,0.734838,0.713886,12500.0,2022-01-20 13:16:00,212.226937,0.000216,100.231527,0.0,61384.831486,0.099885,...,2.050818,0.107938,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,8
403478,0.811084,0.790613,12500.0,2022-01-20 13:18:00,212.221775,0.000215,100.230606,0.0,61243.055229,0.099885,...,2.051106,0.107953,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,9
403478,0.887331,0.867340,12500.0,2022-01-20 13:20:00,212.216482,0.000215,100.230606,0.0,61101.265886,0.099885,...,2.051106,0.107953,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,10

In [7]:
pl_df = load_pl_df(job_ids, outputs_dir)

pl_df[pl_df["time"] == pd.Timestamp('2022-01-20 13:58:00')]["age"]

job_id
403478   0 days 01:00:00
403478   0 days 00:58:00
403478   0 days 00:56:00
403478   0 days 00:54:00
403478   0 days 00:52:00
403478   0 days 00:50:00
403478   0 days 00:48:00
403478   0 days 00:46:00
403478   0 days 00:44:00
403478   0 days 00:42:00
403478   0 days 00:40:00
Name: age, dtype: timedelta64[ns]

In [59]:
chem_ds = load_chem_ds(job_ids, outputs_dir)

chem_ds_stacked = chem_ds.stack(
            {"cell": ["level", "longitude", "latitude"]}
        )
chem_ds_stacked = chem_ds_stacked.reset_index("cell")

chem_ds_stacked = chem_ds_stacked.assign_coords(species_out=chem_ds_stacked.attrs["species_out"])


max_emi_cell = chem_ds_stacked["emi"].mean(dim="time").argmax()#.item()

# find cell that has max emissions averaged over time in it
cell_chem_ds = chem_ds_stacked.sel(job_id=job_ids[0], cell=max_emi_cell)
cell_chem_ds["emi"].sel(emi_species="CO")

# Select the emissions for the specified species
emi_data = cell_chem_ds["emi"].sel(emi_species="CO")

# Convert time and emi data to pandas Series
time_series = pd.Series(emi_data["time"].values)
emi_series = pd.Series(emi_data.values)

# Print time and emi values side by side
for time, emi in zip(time_series, emi_series):
    print(f"Time: {time}, EMI: {emi}")

Time: 2022-01-20 12:00:00, EMI: 0.0
Time: 2022-01-20 12:00:20, EMI: 0.0
Time: 2022-01-20 12:00:40, EMI: 0.0
Time: 2022-01-20 12:01:00, EMI: 0.0
Time: 2022-01-20 12:01:20, EMI: 0.0
Time: 2022-01-20 12:01:40, EMI: 0.0
Time: 2022-01-20 12:02:00, EMI: 0.0
Time: 2022-01-20 12:02:20, EMI: 0.0
Time: 2022-01-20 12:02:40, EMI: 0.0
Time: 2022-01-20 12:03:00, EMI: 0.0
Time: 2022-01-20 12:03:20, EMI: 0.0
Time: 2022-01-20 12:03:40, EMI: 0.0
Time: 2022-01-20 12:04:00, EMI: 0.0
Time: 2022-01-20 12:04:20, EMI: 0.0
Time: 2022-01-20 12:04:40, EMI: 0.0
Time: 2022-01-20 12:05:00, EMI: 0.0
Time: 2022-01-20 12:05:20, EMI: 0.0
Time: 2022-01-20 12:05:40, EMI: 0.0
Time: 2022-01-20 12:06:00, EMI: 0.0
Time: 2022-01-20 12:06:20, EMI: 0.0
Time: 2022-01-20 12:06:40, EMI: 0.0
Time: 2022-01-20 12:07:00, EMI: 0.0
Time: 2022-01-20 12:07:20, EMI: 0.0
Time: 2022-01-20 12:07:40, EMI: 0.0
Time: 2022-01-20 12:08:00, EMI: 0.0
Time: 2022-01-20 12:08:20, EMI: 0.0
Time: 2022-01-20 12:08:40, EMI: 0.0
Time: 2022-01-20 12:09:00, EMI: 0.0
Time: 2022-01-20 12:09:20, EMI: 0.0
Time: 2022-01-20 12:09:40, EMI: 0.0
Time: 2022-01-20 12:10:00, EMI: 0.0
Time: 2022-01-20 12:10:20, EMI: 0.0
Time: 2022-01-20 12:10:40, EMI: 0.0
Time: 2022-01-20 12:11:00, EMI: 0.0
Time: 2022-01-20 12:11:20, EMI: 0.0
Time: 2022-01-20 12:11:40, EMI: 0.0
Time: 2022-01-20 12:12:00, EMI: 0.0
Time: 2022-01-20 12:12:20, EMI: 0.0
Time: 2022-01-20 12:12:40, EMI: 0.0
Time: 2022-01-20 12:13:00, EMI: 0.0
Time: 2022-01-20 12:13:20, EMI: 0.0
Time: 2022-01-20 12:13:40, EMI: 0.0
Time: 2022-01-20 12:14:00, EMI: 0.0
Time: 2022-01-20 12:14:20, EMI: 0.0
Time: 2022-01-20 12:14:40, EMI: 0.0
Time: 2022-01-20 12:15:00, EMI: 0.0
Time: 2022-01-20 12:15:20, EMI: 0.0
Time: 2022-01-20 12:15:40, EMI: 0.0
Time: 2022-01-20 12:16:00, EMI: 0.0
Time: 2022-01-20 12:16:20, EMI: 0.0
Time: 2022-01-20 12:16:40, EMI: 0.0
Time: 2022-01-20 12:17:00, EMI: 0.0
Time: 2022-01-20 12:17:20, EMI: 0.0
Time: 2022-01-20 12:17:40, EMI: 0.0
Time: 2022-01-20 12:18:00, EMI: 0.0
Time: 2022-01-20 12:18:20, EMI: 0.0
Time: 2022-01-20 12:18:40, EMI: 0.0
Time: 2022-01-20 12:19:00, EMI: 0.0
Time: 2022-01-20 12:19:20, EMI: 0.0
Time: 2022-01-20 12:19:40, EMI: 0.0
Time: 2022-01-20 12:20:00, EMI: 0.0
Time: 2022-01-20 12:20:20, EMI: 0.0
Time: 2022-01-20 12:20:40, EMI: 0.0
Time: 2022-01-20 12:21:00, EMI: 0.0
Time: 2022-01-20 12:21:20, EMI: 0.0
Time: 2022-01-20 12:21:40, EMI: 0.0
Time: 2022-01-20 12:22:00, EMI: 0.0
Time: 2022-01-20 12:22:20, EMI: 0.0
Time: 2022-01-20 12:22:40, EMI: 0.0
Time: 2022-01-20 12:23:00, EMI: 0.0
Time: 2022-01-20 12:23:20, EMI: 0.0
Time: 2022-01-20 12:23:40, EMI: 0.0
Time: 2022-01-20 12:24:00, EMI: 0.0
Time: 2022-01-20 12:24:20, EMI: 0.0
Time: 2022-01-20 12:24:40, EMI: 0.0
Time: 2022-01-20 12:25:00, EMI: 0.0
Time: 2022-01-20 12:25:20, EMI: 0.0
Time: 2022-01-20 12:25:40, EMI: 0.0
Time: 2022-01-20 12:26:00, EMI: 0.0
Time: 2022-01-20 12:26:20, EMI: 0.0
Time: 2022-01-20 12:26:40, EMI: 0.0
Time: 2022-01-20 12:27:00, EMI: 0.0
Time: 2022-01-20 12:27:20, EMI: 0.0
Time: 2022-01-20 12:27:40, EMI: 0.0
Time: 2022-01-20 12:28:00, EMI: 0.0
Time: 2022-01-20 12:28:20, EMI: 0.0
Time: 2022-01-20 12:28:40, EMI: 0.0
Time: 2022-01-20 12:29:00, EMI: 0.0
Time: 2022-01-20 12:29:20, EMI: 0.0
Time: 2022-01-20 12:29:40, EMI: 0.0
Time: 2022-01-20 12:30:00, EMI: 0.0
Time: 2022-01-20 12:30:20, EMI: 0.0
Time: 2022-01-20 12:30:40, EMI: 0.0
Time: 2022-01-20 12:31:00, EMI: 0.0
Time: 2022-01-20 12:31:20, EMI: 0.0
Time: 2022-01-20 12:31:40, EMI: 0.0
Time: 2022-01-20 12:32:00, EMI: 0.0
Time: 2022-01-20 12:32:20, EMI: 0.0
Time: 2022-01-20 12:32:40, EMI: 0.0
Time: 2022-01-20 12:33:00, EMI: 0.0
Time: 2022-01-20 12:33:20, EMI: 0.0
Time: 2022-01-20 12:33:40, EMI: 0.0
Time: 2022-01-20 12:34:00, EMI: 0.0
Time: 2022-01-20 12:34:20, EMI: 0.0
Time: 2022-01-20 12:34:40, EMI: 0.0
Time: 2022-01-20 12:35:00, EMI: 0.0
Time: 2022-01-20 12:35:20, EMI: 0.0
Time: 2022-01-20 12:35:40, EMI: 0.0
Time: 2022-01-20 12:36:00, EMI: 0.0
Time: 2022-01-20 12:36:20, EMI: 0.0
Time: 2022-01-20 12:36:40, EMI: 0.0
Time: 2022-01-20 12:37:00, EMI: 0.0
Time: 2022-01-20 12:37:20, EMI: 0.0
Time: 2022-01-20 12:37:40, EMI: 0.0
Time: 2022-01-20 12:38:00, EMI: 0.0
Time: 2022-01-20 12:38:20, EMI: 0.0
Time: 2022-01-20 12:38:40, EMI: 0.0
Time: 2022-01-20 12:39:00, EMI: 0.0
Time: 2022-01-20 12:39:20, EMI: 0.0
Time: 2022-01-20 12:39:40, EMI: 0.0
Time: 2022-01-20 12:40:00, EMI: 0.0
Time: 2022-01-20 12:40:20, EMI: 0.0
Time: 2022-01-20 12:40:40, EMI: 0.0
Time: 2022-01-20 12:41:00, EMI: 0.0
Time: 2022-01-20 12:41:20, EMI: 0.0
Time: 2022-01-20 12:41:40, EMI: 0.0
Time: 2022-01-20 12:42:00, EMI: 0.0
Time: 2022-01-20 12:42:20, EMI: 0.0
Time: 2022-01-20 12:42:40, EMI: 0.0
Time: 2022-01-20 12:43:00, EMI: 0.0
Time: 2022-01-20 12:43:20, EMI: 0.0
Time: 2022-01-20 12:43:40, EMI: 0.0
Time: 2022-01-20 12:44:00, EMI: 0.0
Time: 2022-01-20 12:44:20, EMI: 0.0
Time: 2022-01-20 12:44:40, EMI: 0.0
Time: 2022-01-20 12:45:00, EMI: 0.0
Time: 2022-01-20 12:45:20, EMI: 0.0
Time: 2022-01-20 12:45:40, EMI: 0.0
Time: 2022-01-20 12:46:00, EMI: 0.0
Time: 2022-01-20 12:46:20, EMI: 0.0
Time: 2022-01-20 12:46:40, EMI: 0.0
Time: 2022-01-20 12:47:00, EMI: 0.0
Time: 2022-01-20 12:47:20, EMI: 0.0
Time: 2022-01-20 12:47:40, EMI: 0.0
Time: 2022-01-20 12:48:00, EMI: 0.0
Time: 2022-01-20 12:48:20, EMI: 0.0
Time: 2022-01-20 12:48:40, EMI: 0.0
Time: 2022-01-20 12:49:00, EMI: 0.0
Time: 2022-01-20 12:49:20, EMI: 0.0
Time: 2022-01-20 12:49:40, EMI: 0.0
Time: 2022-01-20 12:50:00, EMI: 0.0
Time: 2022-01-20 12:50:20, EMI: 0.0
Time: 2022-01-20 12:50:40, EMI: 0.0
Time: 2022-01-20 12:51:00, EMI: 0.0
Time: 2022-01-20 12:51:20, EMI: 0.0
Time: 2022-01-20 12:51:40, EMI: 0.0
Time: 2022-01-20 12:52:00, EMI: 0.0
Time: 2022-01-20 12:52:20, EMI: 0.0
Time: 2022-01-20 12:52:40, EMI: 0.0
Time: 2022-01-20 12:53:00, EMI: 0.0
Time: 2022-01-20 12:53:20, EMI: 0.0
Time: 2022-01-20 12:53:40, EMI: 0.0
Time: 2022-01-20 12:54:00, EMI: 0.0
Time: 2022-01-20 12:54:20, EMI: 0.0
Time: 2022-01-20 12:54:40, EMI: 0.0
Time: 2022-01-20 12:55:00, EMI: 0.0
Time: 2022-01-20 12:55:20, EMI: 0.0
Time: 2022-01-20 12:55:40, EMI: 0.0
Time: 2022-01-20 12:56:00, EMI: 0.0
Time: 2022-01-20 12:56:20, EMI: 0.0
Time: 2022-01-20 12:56:40, EMI: 0.0
Time: 2022-01-20 12:57:00, EMI: 0.0
Time: 2022-01-20 12:57:20, EMI: 0.0
Time: 2022-01-20 12:57:40, EMI: 0.0
Time: 2022-01-20 12:58:00, EMI: 0.0
Time: 2022-01-20 12:58:20, EMI: 0.0
Time: 2022-01-20 12:58:40, EMI: 0.0
Time: 2022-01-20 12:59:00, EMI: 0.0
Time: 2022-01-20 12:59:20, EMI: 0.0
Time: 2022-01-20 12:59:40, EMI: 0.0
Time: 2022-01-20 13:00:00, EMI: 0.0
Time: 2022-01-20 13:00:20, EMI: 0.0
Time: 2022-01-20 13:00:40, EMI: 0.0
Time: 2022-01-20 13:01:00, EMI: 0.0
Time: 2022-01-20 13:01:20, EMI: 0.0
Time: 2022-01-20 13:01:40, EMI: 0.0
Time: 2022-01-20 13:02:00, EMI: 0.0
Time: 2022-01-20 13:02:20, EMI: 0.0
Time: 2022-01-20 13:02:40, EMI: 0.0
Time: 2022-01-20 13:03:00, EMI: 0.0
Time: 2022-01-20 13:03:20, EMI: 0.0
Time: 2022-01-20 13:03:40, EMI: 0.0
Time: 2022-01-20 13:04:00, EMI: 0.0
Time: 2022-01-20 13:04:20, EMI: 0.0
Time: 2022-01-20 13:04:40, EMI: 0.0
Time: 2022-01-20 13:05:00, EMI: 0.0
Time: 2022-01-20 13:05:20, EMI: 0.0
Time: 2022-01-20 13:05:40, EMI: 0.0
Time: 2022-01-20 13:06:00, EMI: 0.0
Time: 2022-01-20 13:06:20, EMI: 0.0
Time: 2022-01-20 13:06:40, EMI: 0.0
Time: 2022-01-20 13:07:00, EMI: 0.0
Time: 2022-01-20 13:07:20, EMI: 0.0
Time: 2022-01-20 13:07:40, EMI: 0.0
Time: 2022-01-20 13:08:00, EMI: 0.0
Time: 2022-01-20 13:08:20, EMI: 0.0
Time: 2022-01-20 13:08:40, EMI: 0.0
Time: 2022-01-20 13:09:00, EMI: 0.0
Time: 2022-01-20 13:09:20, EMI: 0.0
Time: 2022-01-20 13:09:40, EMI: 0.0
Time: 2022-01-20 13:10:00, EMI: 0.0
Time: 2022-01-20 13:10:20, EMI: 0.0
Time: 2022-01-20 13:10:40, EMI: 0.0
Time: 2022-01-20 13:11:00, EMI: 0.0
Time: 2022-01-20 13:11:20, EMI: 0.0
Time: 2022-01-20 13:11:40, EMI: 0.0
Time: 2022-01-20 13:12:00, EMI: 0.0
Time: 2022-01-20 13:12:20, EMI: 0.0
Time: 2022-01-20 13:12:40, EMI: 0.0
Time: 2022-01-20 13:13:00, EMI: 0.0
Time: 2022-01-20 13:13:20, EMI: 0.0
Time: 2022-01-20 13:13:40, EMI: 0.0
Time: 2022-01-20 13:14:00, EMI: 0.0
Time: 2022-01-20 13:14:20, EMI: 0.0
Time: 2022-01-20 13:14:40, EMI: 0.0
Time: 2022-01-20 13:15:00, EMI: 0.0
Time: 2022-01-20 13:15:20, EMI: 0.0
Time: 2022-01-20 13:15:40, EMI: 0.0
Time: 2022-01-20 13:16:00, EMI: 0.0
Time: 2022-01-20 13:16:20, EMI: 0.0
Time: 2022-01-20 13:16:40, EMI: 0.0
Time: 2022-01-20 13:17:00, EMI: 0.0
Time: 2022-01-20 13:17:20, EMI: 0.0
Time: 2022-01-20 13:17:40, EMI: 0.0
Time: 2022-01-20 13:18:00, EMI: 0.0
Time: 2022-01-20 13:18:20, EMI: 0.0
Time: 2022-01-20 13:18:40, EMI: 0.0
Time: 2022-01-20 13:19:00, EMI: 0.0
Time: 2022-01-20 13:19:20, EMI: 0.0
Time: 2022-01-20 13:19:40, EMI: 0.0
Time: 2022-01-20 13:20:00, EMI: 37268050.897921905
Time: 2022-01-20 13:20:20, EMI: 0.0
Time: 2022-01-20 13:20:40, EMI: 0.0
Time: 2022-01-20 13:21:00, EMI: 0.0
Time: 2022-01-20 13:21:20, EMI: 0.0
Time: 2022-01-20 13:21:40, EMI: 0.0
Time: 2022-01-20 13:22:00, EMI: 36300945.75532794
Time: 2022-01-20 13:22:20, EMI: 0.0
Time: 2022-01-20 13:22:40, EMI: 0.0
Time: 2022-01-20 13:23:00, EMI: 0.0
Time: 2022-01-20 13:23:20, EMI: 0.0
Time: 2022-01-20 13:23:40, EMI: 0.0
Time: 2022-01-20 13:24:00, EMI: 35675552.59611389
Time: 2022-01-20 13:24:20, EMI: 0.0
Time: 2022-01-20 13:24:40, EMI: 0.0
Time: 2022-01-20 13:25:00, EMI: 0.0
Time: 2022-01-20 13:25:20, EMI: 0.0
Time: 2022-01-20 13:25:40, EMI: 0.0
Time: 2022-01-20 13:26:00, EMI: 35278220.54606814
Time: 2022-01-20 13:26:20, EMI: 0.0
Time: 2022-01-20 13:26:40, EMI: 0.0
Time: 2022-01-20 13:27:00, EMI: 0.0
Time: 2022-01-20 13:27:20, EMI: 0.0
Time: 2022-01-20 13:27:40, EMI: 0.0
Time: 2022-01-20 13:28:00, EMI: 35007564.683375955
Time: 2022-01-20 13:28:20, EMI: 0.0
Time: 2022-01-20 13:28:40, EMI: 0.0
Time: 2022-01-20 13:29:00, EMI: 0.0
Time: 2022-01-20 13:29:20, EMI: 0.0
Time: 2022-01-20 13:29:40, EMI: 0.0
Time: 2022-01-20 13:30:00, EMI: 34811964.26638522
Time: 2022-01-20 13:30:20, EMI: 0.0
Time: 2022-01-20 13:30:40, EMI: 0.0
Time: 2022-01-20 13:31:00, EMI: 0.0
Time: 2022-01-20 13:31:20, EMI: 0.0
Time: 2022-01-20 13:31:40, EMI: 0.0
Time: 2022-01-20 13:32:00, EMI: 34664068.42327589
Time: 2022-01-20 13:32:20, EMI: 0.0
Time: 2022-01-20 13:32:40, EMI: 0.0
Time: 2022-01-20 13:33:00, EMI: 0.0
Time: 2022-01-20 13:33:20, EMI: 0.0
Time: 2022-01-20 13:33:40, EMI: 0.0
Time: 2022-01-20 13:34:00, EMI: 34548292.02879323
Time: 2022-01-20 13:34:20, EMI: 0.0
Time: 2022-01-20 13:34:40, EMI: 0.0
Time: 2022-01-20 13:35:00, EMI: 0.0
Time: 2022-01-20 13:35:20, EMI: 0.0
Time: 2022-01-20 13:35:40, EMI: 0.0
Time: 2022-01-20 13:36:00, EMI: 34455157.726938024
Time: 2022-01-20 13:36:20, EMI: 0.0
Time: 2022-01-20 13:36:40, EMI: 0.0
Time: 2022-01-20 13:37:00, EMI: 0.0
Time: 2022-01-20 13:37:20, EMI: 0.0
Time: 2022-01-20 13:37:40, EMI: 0.0
Time: 2022-01-20 13:38:00, EMI: 34378583.69211383
Time: 2022-01-20 13:38:20, EMI: 0.0
Time: 2022-01-20 13:38:40, EMI: 0.0
Time: 2022-01-20 13:39:00, EMI: 0.0
Time: 2022-01-20 13:39:20, EMI: 0.0
Time: 2022-01-20 13:39:40, EMI: 0.0
Time: 2022-01-20 13:40:00, EMI: 34314490.77097897
Time: 2022-01-20 13:40:20, EMI: 0.0
Time: 2022-01-20 13:40:40, EMI: 0.0
Time: 2022-01-20 13:41:00, EMI: 0.0
Time: 2022-01-20 13:41:20, EMI: 0.0
Time: 2022-01-20 13:41:40, EMI: 0.0
Time: 2022-01-20 13:42:00, EMI: 34260041.14251187
Time: 2022-01-20 13:42:20, EMI: 0.0
Time: 2022-01-20 13:42:40, EMI: 0.0
Time: 2022-01-20 13:43:00, EMI: 0.0
Time: 2022-01-20 13:43:20, EMI: 0.0
Time: 2022-01-20 13:43:40, EMI: 0.0
Time: 2022-01-20 13:44:00, EMI: 34213199.20993395
Time: 2022-01-20 13:44:20, EMI: 0.0
Time: 2022-01-20 13:44:40, EMI: 0.0
Time: 2022-01-20 13:45:00, EMI: 0.0
Time: 2022-01-20 13:45:20, EMI: 0.0
Time: 2022-01-20 13:45:40, EMI: 0.0
Time: 2022-01-20 13:46:00, EMI: 34172466.46981541
Time: 2022-01-20 13:46:20, EMI: 0.0
Time: 2022-01-20 13:46:40, EMI: 0.0
Time: 2022-01-20 13:47:00, EMI: 0.0
Time: 2022-01-20 13:47:20, EMI: 0.0
Time: 2022-01-20 13:47:40, EMI: 0.0
Time: 2022-01-20 13:48:00, EMI: 34136715.02742903
Time: 2022-01-20 13:48:20, EMI: 0.0
Time: 2022-01-20 13:48:40, EMI: 0.0
Time: 2022-01-20 13:49:00, EMI: 0.0
Time: 2022-01-20 13:49:20, EMI: 0.0
Time: 2022-01-20 13:49:40, EMI: 0.0
Time: 2022-01-20 13:50:00, EMI: 34105079.464596406
Time: 2022-01-20 13:50:20, EMI: 0.0
Time: 2022-01-20 13:50:40, EMI: 0.0
Time: 2022-01-20 13:51:00, EMI: 0.0
Time: 2022-01-20 13:51:20, EMI: 0.0
Time: 2022-01-20 13:51:40, EMI: 0.0
Time: 2022-01-20 13:52:00, EMI: 34076884.51788318
Time: 2022-01-20 13:52:20, EMI: 0.0
Time: 2022-01-20 13:52:40, EMI: 0.0
Time: 2022-01-20 13:53:00, EMI: 0.0
Time: 2022-01-20 13:53:20, EMI: 0.0
Time: 2022-01-20 13:53:40, EMI: 0.0
Time: 2022-01-20 13:54:00, EMI: 34051595.450764515
Time: 2022-01-20 13:54:20, EMI: 0.0
Time: 2022-01-20 13:54:40, EMI: 0.0
Time: 2022-01-20 13:55:00, EMI: 0.0
Time: 2022-01-20 13:55:20, EMI: 0.0
Time: 2022-01-20 13:55:40, EMI: 0.0
Time: 2022-01-20 13:56:00, EMI: 34028783.21975541
Time: 2022-01-20 13:56:20, EMI: 0.0
Time: 2022-01-20 13:56:40, EMI: 0.0
Time: 2022-01-20 13:57:00, EMI: 0.0
Time: 2022-01-20 13:57:20, EMI: 0.0
Time: 2022-01-20 13:57:40, EMI: 0.0
Time: 2022-01-20 13:58:00, EMI: 34007976.532724924
Time: 2022-01-20 13:58:20, EMI: 0.0
Time: 2022-01-20 13:58:40, EMI: 0.0
Time: 2022-01-20 13:59:00, EMI: 0.0
Time: 2022-01-20 13:59:20, EMI: 0.0
Time: 2022-01-20 13:59:40, EMI: 0.0
Time: 2022-01-20 14:00:00, EMI: 33986927.83242117
Time: 2022-01-20 14:00:20, EMI: 0.0
Time: 2022-01-20 14:00:40, EMI: 0.0
Time: 2022-01-20 14:01:00, EMI: 0.0
Time: 2022-01-20 14:01:20, EMI: 0.0
Time: 2022-01-20 14:01:40, EMI: 0.0
Time: 2022-01-20 14:02:00, EMI: 33952660.75406735
Time: 2022-01-20 14:02:20, EMI: 0.0
Time: 2022-01-20 14:02:40, EMI: 0.0
Time: 2022-01-20 14:03:00, EMI: 0.0
Time: 2022-01-20 14:03:20, EMI: 0.0
Time: 2022-01-20 14:03:40, EMI: 0.0
Time: 2022-01-20 14:04:00, EMI: 33902561.49685901
Time: 2022-01-20 14:04:20, EMI: 0.0
Time: 2022-01-20 14:04:40, EMI: 0.0
Time: 2022-01-20 14:05:00, EMI: 0.0
Time: 2022-01-20 14:05:20, EMI: 0.0
Time: 2022-01-20 14:05:40, EMI: 0.0
Time: 2022-01-20 14:06:00, EMI: 33838361.765656434
Time: 2022-01-20 14:06:20, EMI: 0.0
Time: 2022-01-20 14:06:40, EMI: 0.0
Time: 2022-01-20 14:07:00, EMI: 0.0
Time: 2022-01-20 14:07:20, EMI: 0.0
Time: 2022-01-20 14:07:40, EMI: 0.0
Time: 2022-01-20 14:08:00, EMI: 33761486.11745945
Time: 2022-01-20 14:08:20, EMI: 0.0
Time: 2022-01-20 14:08:40, EMI: 0.0
Time: 2022-01-20 14:09:00, EMI: 0.0
Time: 2022-01-20 14:09:20, EMI: 0.0
Time: 2022-01-20 14:09:40, EMI: 0.0
Time: 2022-01-20 14:10:00, EMI: 33672668.106577024
Time: 2022-01-20 14:10:20, EMI: 0.0
Time: 2022-01-20 14:10:40, EMI: 0.0
Time: 2022-01-20 14:11:00, EMI: 0.0
Time: 2022-01-20 14:11:20, EMI: 0.0
Time: 2022-01-20 14:11:40, EMI: 0.0
Time: 2022-01-20 14:12:00, EMI: 33565216.88371451
Time: 2022-01-20 14:12:20, EMI: 0.0
Time: 2022-01-20 14:12:40, EMI: 0.0
Time: 2022-01-20 14:13:00, EMI: 0.0
Time: 2022-01-20 14:13:20, EMI: 0.0
Time: 2022-01-20 14:13:40, EMI: 0.0
Time: 2022-01-20 14:14:00, EMI: 33440118.339985266
Time: 2022-01-20 14:14:20, EMI: 0.0
Time: 2022-01-20 14:14:40, EMI: 0.0
Time: 2022-01-20 14:15:00, EMI: 0.0
Time: 2022-01-20 14:15:20, EMI: 0.0
Time: 2022-01-20 14:15:40, EMI: 0.0
Time: 2022-01-20 14:16:00, EMI: 33292460.605487674
Time: 2022-01-20 14:16:20, EMI: 0.0
Time: 2022-01-20 14:16:40, EMI: 0.0
Time: 2022-01-20 14:17:00, EMI: 0.0
Time: 2022-01-20 14:17:20, EMI: 0.0
Time: 2022-01-20 14:17:40, EMI: 0.0
Time: 2022-01-20 14:18:00, EMI: 0.0
Time: 2022-01-20 14:18:20, EMI: 0.0
Time: 2022-01-20 14:18:40, EMI: 0.0
Time: 2022-01-20 14:19:00, EMI: 0.0
Time: 2022-01-20 14:19:20, EMI: 0.0
Time: 2022-01-20 14:19:40, EMI: 0.0
Time: 2022-01-20 14:20:00, EMI: 0.0
Time: 2022-01-20 14:20:20, EMI: 0.0
Time: 2022-01-20 14:20:40, EMI: 0.0
Time: 2022-01-20 14:21:00, EMI: 0.0
Time: 2022-01-20 14:21:20, EMI: 0.0
Time: 2022-01-20 14:21:40, EMI: 0.0
Time: 2022-01-20 14:22:00, EMI: 0.0
Time: 2022-01-20 14:22:20, EMI: 0.0
Time: 2022-01-20 14:22:40, EMI: 0.0
Time: 2022-01-20 14:23:00, EMI: 0.0
Time: 2022-01-20 14:23:20, EMI: 0.0
Time: 2022-01-20 14:23:40, EMI: 0.0
Time: 2022-01-20 14:24:00, EMI: 0.0
Time: 2022-01-20 14:24:20, EMI: 0.0
Time: 2022-01-20 14:24:40, EMI: 0.0
Time: 2022-01-20 14:25:00, EMI: 0.0
Time: 2022-01-20 14:25:20, EMI: 0.0
Time: 2022-01-20 14:25:40, EMI: 0.0
Time: 2022-01-20 14:26:00, EMI: 0.0
Time: 2022-01-20 14:26:20, EMI: 0.0
Time: 2022-01-20 14:26:40, EMI: 0.0
Time: 2022-01-20 14:27:00, EMI: 0.0
Time: 2022-01-20 14:27:20, EMI: 0.0
Time: 2022-01-20 14:27:40, EMI: 0.0
Time: 2022-01-20 14:28:00, EMI: 0.0
Time: 2022-01-20 14:28:20, EMI: 0.0
Time: 2022-01-20 14:28:40, EMI: 0.0
Time: 2022-01-20 14:29:00, EMI: 0.0
Time: 2022-01-20 14:29:20, EMI: 0.0
Time: 2022-01-20 14:29:40, EMI: 0.0
Time: 2022-01-20 14:30:00, EMI: 0.0
Time: 2022-01-20 14:30:20, EMI: 0.0
Time: 2022-01-20 14:30:40, EMI: 0.0
Time: 2022-01-20 14:31:00, EMI: 0.0
Time: 2022-01-20 14:31:20, EMI: 0.0
Time: 2022-01-20 14:31:40, EMI: 0.0
Time: 2022-01-20 14:32:00, EMI: 0.0
Time: 2022-01-20 14:32:20, EMI: 0.0
Time: 2022-01-20 14:32:40, EMI: 0.0
Time: 2022-01-20 14:33:00, EMI: 0.0
Time: 2022-01-20 14:33:20, EMI: 0.0
Time: 2022-01-20 14:33:40, EMI: 0.0
Time: 2022-01-20 14:34:00, EMI: 0.0
Time: 2022-01-20 14:34:20, EMI: 0.0
Time: 2022-01-20 14:34:40, EMI: 0.0
Time: 2022-01-20 14:35:00, EMI: 0.0
Time: 2022-01-20 14:35:20, EMI: 0.0
Time: 2022-01-20 14:35:40, EMI: 0.0
Time: 2022-01-20 14:36:00, EMI: 0.0
Time: 2022-01-20 14:36:20, EMI: 0.0
Time: 2022-01-20 14:36:40, EMI: 0.0
Time: 2022-01-20 14:37:00, EMI: 0.0
Time: 2022-01-20 14:37:20, EMI: 0.0
Time: 2022-01-20 14:37:40, EMI: 0.0
Time: 2022-01-20 14:38:00, EMI: 0.0
Time: 2022-01-20 14:38:20, EMI: 0.0
Time: 2022-01-20 14:38:40, EMI: 0.0
Time: 2022-01-20 14:39:00, EMI: 0.0
Time: 2022-01-20 14:39:20, EMI: 0.0
Time: 2022-01-20 14:39:40, EMI: 0.0
Time: 2022-01-20 14:40:00, EMI: 0.0
Time: 2022-01-20 14:40:20, EMI: 0.0
Time: 2022-01-20 14:40:40, EMI: 0.0
Time: 2022-01-20 14:41:00, EMI: 0.0
Time: 2022-01-20 14:41:20, EMI: 0.0
Time: 2022-01-20 14:41:40, EMI: 0.0
Time: 2022-01-20 14:42:00, EMI: 0.0
Time: 2022-01-20 14:42:20, EMI: 0.0
Time: 2022-01-20 14:42:40, EMI: 0.0
Time: 2022-01-20 14:43:00, EMI: 0.0
Time: 2022-01-20 14:43:20, EMI: 0.0
Time: 2022-01-20 14:43:40, EMI: 0.0
Time: 2022-01-20 14:44:00, EMI: 0.0
Time: 2022-01-20 14:44:20, EMI: 0.0
Time: 2022-01-20 14:44:40, EMI: 0.0
Time: 2022-01-20 14:45:00, EMI: 0.0
Time: 2022-01-20 14:45:20, EMI: 0.0
Time: 2022-01-20 14:45:40, EMI: 0.0
Time: 2022-01-20 14:46:00, EMI: 0.0
Time: 2022-01-20 14:46:20, EMI: 0.0
Time: 2022-01-20 14:46:40, EMI: 0.0
Time: 2022-01-20 14:47:00, EMI: 0.0
Time: 2022-01-20 14:47:20, EMI: 0.0
Time: 2022-01-20 14:47:40, EMI: 0.0
Time: 2022-01-20 14:48:00, EMI: 0.0
Time: 2022-01-20 14:48:20, EMI: 0.0
Time: 2022-01-20 14:48:40, EMI: 0.0
Time: 2022-01-20 14:49:00, EMI: 0.0
Time: 2022-01-20 14:49:20, EMI: 0.0
Time: 2022-01-20 14:49:40, EMI: 0.0
Time: 2022-01-20 14:50:00, EMI: 0.0
Time: 2022-01-20 14:50:20, EMI: 0.0
Time: 2022-01-20 14:50:40, EMI: 0.0
Time: 2022-01-20 14:51:00, EMI: 0.0
Time: 2022-01-20 14:51:20, EMI: 0.0
Time: 2022-01-20 14:51:40, EMI: 0.0
Time: 2022-01-20 14:52:00, EMI: 0.0
Time: 2022-01-20 14:52:20, EMI: 0.0
Time: 2022-01-20 14:52:40, EMI: 0.0
Time: 2022-01-20 14:53:00, EMI: 0.0
Time: 2022-01-20 14:53:20, EMI: 0.0
Time: 2022-01-20 14:53:40, EMI: 0.0
Time: 2022-01-20 14:54:00, EMI: 0.0
Time: 2022-01-20 14:54:20, EMI: 0.0
Time: 2022-01-20 14:54:40, EMI: 0.0
Time: 2022-01-20 14:55:00, EMI: 0.0
Time: 2022-01-20 14:55:20, EMI: 0.0
Time: 2022-01-20 14:55:40, EMI: 0.0
Time: 2022-01-20 14:56:00, EMI: 0.0
Time: 2022-01-20 14:56:20, EMI: 0.0
Time: 2022-01-20 14:56:40, EMI: 0.0
Time: 2022-01-20 14:57:00, EMI: 0.0
Time: 2022-01-20 14:57:20, EMI: 0.0
Time: 2022-01-20 14:57:40, EMI: 0.0
Time: 2022-01-20 14:58:00, EMI: 0.0
Time: 2022-01-20 14:58:20, EMI: 0.0
Time: 2022-01-20 14:58:40, EMI: 0.0
Time: 2022-01-20 14:59:00, EMI: 0.0
Time: 2022-01-20 14:59:20, EMI: 0.0
Time: 2022-01-20 14:59:40, EMI: 0.0
Time: 2022-01-20 15:00:00, EMI: 0.0
Time: 2022-01-20 15:00:20, EMI: 0.0
Time: 2022-01-20 15:00:40, EMI: 0.0
Time: 2022-01-20 15:01:00, EMI: 0.0

In [39]:
job_id = job_ids[0]
job_id
# mc = mc_test(job_id, jobs_df, fl_df, pl_df, chem_ds)

# mc

'403478'

In [40]:
cell_chem_ds = boxm_test(job_ids[0], 10, chem_ds)