In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xarray as xr
import dask.array as da
import os
from pycontrails.models.gpat.gpat import GPAT, create_jobs_df, filter_jobs_df, load_fl_df, load_pl_df, load_chem_ds, mc_test

In [2]:
outputs_dir = "/user/home/kt16229/work/pycontrails_kt/pycontrails/models/gpat/outputs/"

In [3]:
# Filter criteria
criteria = {
        "n_ac": 1,
        "rt_fl": (pd.Timedelta(minutes=30), pd.Timedelta(hours=2)),
    }

In [4]:
jobs_df = create_jobs_df(outputs_dir)

jobs_df

,t0_fl,rt_fl,ts_fl,ac_type,fl0_speed,fl0_heading,fl0_coords0,sep_dist,n_ac,dt_integration,...,lat_bounds,lon_bounds,alt_bounds,hres_sim,vres_sim,eastward_wind,northward_wind,lagrangian_tendency_of_air_pressure,species_out,date_created
job_id,,,,,,,,,,,,,,,,,,,,,
404714,2022-01-20 13:00:00,0 days 01:00:00,0 days 00:02:00,A320,100.0,45.0,"(0.1, 0.125, 12500)","(5000, 2000, 0)",1,0 days 00:02:00,...,"(0.0, 1.0)","(0.0, 1.0)","(12000, 13000)",0.05,500,0.0,0.0,0.0,"[3, 4, 5, 6, 8, 9]",2024-11-01 12:47:53.008624

In [5]:
filtered_df = filter_jobs_df(jobs_df, criteria)

job_ids = filtered_df.index.values

job_ids

array(['404714'], dtype=object)

In [6]:
fl_df = load_fl_df(job_ids, outputs_dir)

fl_df

,longitude,latitude,altitude,time,air_temperature,specific_humidity,true_airspeed,flight_id,aircraft_mass,engine_efficiency,...,NO,NO2,CO,HCHO,CH3CHO,C2H4,C3H6,C2H2,BENZENE,waypoint
job_id,,,,,,,,,,,,,,,,,,,,,
404714,0.125000,0.100000,12500.0,2022-01-20 13:00:00,212.263516,0.000219,100.230014,0.0,62518.613860,0.099880,...,2.048795,0.107831,0.062205,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,0
404714,0.201229,0.176736,12500.0,2022-01-20 13:02:00,212.259403,0.000218,100.229809,0.0,62376.929746,0.099880,...,2.049022,0.107843,0.062205,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,1
404714,0.277457,0.253473,12500.0,2022-01-20 13:04:00,212.255158,0.000218,100.229514,0.0,62235.235247,0.099881,...,2.049256,0.107856,0.062206,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,2
404714,0.353686,0.330209,12500.0,2022-01-20 13:06:00,212.250782,0.000218,100.229130,0.0,62093.530027,0.099881,...,2.049498,0.107868,0.062206,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,3
404714,0.429914,0.406945,12500.0,2022-01-20 13:08:00,212.246275,0.000217,100.228656,0.0,61951.813748,0.099881,...,2.049747,0.107881,0.062207,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,4
404714,0.506143,0.483682,12500.0,2022-01-20 13:10:00,212.241637,0.000217,100.228093,0.0,61810.086073,0.099882,...,2.050005,0.107895,0.062208,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,5
404714,0.582371,0.560418,12500.0,2022-01-20 13:12:00,212.236868,0.000217,100.227441,0.0,61668.346665,0.099882,...,2.050270,0.107909,0.062208,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,6
404714,0.658600,0.637154,12500.0,2022-01-20 13:14:00,212.231968,0.000216,100.229528,0.0,61526.595186,0.099884,...,2.050540,0.107923,0.062209,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,7
404714,0.734838,0.713886,12500.0,2022-01-20 13:16:00,212.226937,0.000216,100.231527,0.0,61384.831486,0.099885,...,2.050818,0.107938,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,8
404714,0.811084,0.790613,12500.0,2022-01-20 13:18:00,212.221775,0.000215,100.230606,0.0,61243.055229,0.099885,...,2.051106,0.107953,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,9
404714,0.887331,0.867340,12500.0,2022-01-20 13:20:00,212.216482,0.000215,100.230606,0.0,61101.265886,0.099885,...,2.051106,0.107953,0.062210,0.000728,0.000243,0.00091,0.000243,0.000243,0.000121,10

In [7]:
pl_df = load_pl_df(job_ids, outputs_dir)

pl_df[pl_df["time"] == pd.Timestamp('2022-01-20 13:58:00')]["age"]

job_id
404714   0 days 01:00:00
404714   0 days 00:58:00
404714   0 days 00:56:00
404714   0 days 00:54:00
404714   0 days 00:52:00
404714   0 days 00:50:00
404714   0 days 00:48:00
404714   0 days 00:46:00
404714   0 days 00:44:00
404714   0 days 00:42:00
404714   0 days 00:40:00
Name: age, dtype: timedelta64[ns]

In [8]:
chem_ds = load_chem_ds(job_ids, outputs_dir)

/user/home/kt16229/BOXM/scratch/miniconda3/envs/contrails/lib/python3.12/site-packages/xarray/backends/plugins.py:80: RuntimeWarning: Engine 'cfgrib' loading failed:
Cannot find the ecCodes library
  warnings.warn(f"Engine {name!r} loading failed:\n{ex}", RuntimeWarning)

In [9]:
mc_test(job_ids, jobs_df, fl_df, pl_df, chem_ds)

time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00
time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00
time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00
time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00
time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00
time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00
time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00
time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00
time: 0 2022-01-20 13:00:00
time: 1 2022-01-20 13:02:00
time: 2 2022-01-20 13:04:00
time: 3 2022-01-20 13:06:00
time: 4 2022-01-20 13:08:00
time: 5 2022-01-20 13:10:00
time: 6 2022-01-20 13:12:00
time: 7 2022-01-20 13:14:00
time: 8 2022-01-20 13:16:00
time: 9 2022-01-20 13:18:00
time: 10 2022-01-20 13:20:00
time: 11 2022-01-20 13:22:00
time: 12 2022-01-20 13:24:00
time: 13 2022-01-20 13:26:00
time: 14 2022-01-20 13:28:00
time: 15 2022-01-20 13:30:00
time: 16 2022-01-20 13:32:00
time: 17 2022-01-20 13:34:00
time: 18 2022-01-20 13:36:00
time: 19 2022-01-20 13:38:00
time: 20 2022-01-20 13:40:00
time: 21 2022-01-20 13:42:00
time: 22 2022-01-20 13:44:00
time: 23 2022-01-20 13:46:00
time: 24 2022-01-20 13:48:00
time: 25 2022-01-20 13:50:00
time: 26 2022-01-20 13:52:00
time: 27 2022-01-20 13:54:00
time: 28 2022-01-20 13:56:00
time: 29 2022-01-20 13:58:00
time: 30 2022-01-20 14:00:00
time: 31 2022-01-20 14:02:00
time: 32 2022-01-20 14:04:00
time: 33 2022-01-20 14:06:00
time: 34 2022-01-20 14:08:00
time: 35 2022-01-20 14:10:00
time: 36 2022-01-20 14:12:00
time: 37 2022-01-20 14:14:00
time: 38 2022-01-20 14:16:00

In [10]:
mc = pd.read_pickle("/user/home/kt16229/work/pycontrails_kt/pycontrails/models/gpat/outputs/" + job_ids[0] + "/mc_" + job_ids[0] + ".pkl")

mc

,NO,NO2,CO,HCHO,CH3CHO,C2H4,C3H6,C2H2,BENZENE
2022-01-20 13:00:00,100.000000,100.000000,100.000000,100,100,100,100,100,100
2022-01-20 13:02:00,98.761044,98.761044,98.756050,100,100,100,100,100,100
2022-01-20 13:04:00,97.679255,97.679255,97.674278,100,100,100,100,100,100
2022-01-20 13:06:00,98.296510,98.296510,98.291315,100,100,100,100,100,100
2022-01-20 13:08:00,96.993656,96.993656,96.988649,100,100,100,100,100,100
2022-01-20 13:10:00,97.418409,97.418409,97.413141,100,100,100,100,100,100
2022-01-20 13:12:00,97.744967,97.744967,97.739474,100,100,100,100,100,100
2022-01-20 13:14:00,98.000800,98.000800,97.995108,100,100,100,100,100,100
2022-01-20 13:16:00,95.588146,95.588146,95.583489,100,100,100,100,100,100
2022-01-20 13:18:00,96.162434,96.162434,96.157292,100,100,100,100,100,100
2022-01-20 13:20:00,95.039297,95.039297,95.035258,100,100,100,100,100,100
2022-01-20 13:22:00,95.137181,95.137181,95.133071,100,100,100,100,100,100
2022-01-20 13:24:00,95.190569,95.190569,95.186408,100,100,100,100,100,100
2022-01-20 13:26:00,97.027838,97.027838,97.023010,100,100,100,100,100,100
2022-01-20 13:28:00,97.015905,97.015905,97.011053,100,100,100,100,100,100
2022-01-20 13:30:00,96.994696,96.994696,96.989821,100,100,100,100,100,100
2022-01-20 13:32:00,96.966566,96.966566,96.961669,100,100,100,100,100,100
2022-01-20 13:34:00,96.933009,96.933009,96.928091,100,100,100,100,100,100
2022-01-20 13:36:00,96.895128,96.895128,96.890190,100,100,100,100,100,100
2022-01-20 13:38:00,96.853290,96.853290,96.848331,100,100,100,100,100,100
2022-01-20 13:40:00,96.807113,96.807113,96.802134,100,100,100,100,100,100
2022-01-20 13:42:00,96.755872,96.755872,96.750872,100,100,100,100,100,100
2022-01-20 13:44:00,98.857205,98.857205,98.851608,100,100,100,100,100,100
2022-01-20 13:46:00,98.796949,98.796949,98.791334,100,100,100,100,100,100
2022-01-20 13:48:00,98.733335,98.733335,98.727700,100,100,100,100,100,100
2022-01-20 13:50:00,99.173047,99.173047,99.167565,100,100,100,100,100,100
2022-01-20 13:52:00,99.111725,99.111725,99.106225,100,100,100,100,100,100
2022-01-20 13:54:00,99.631634,99.631634,99.626377,100,100,100,100,100,100
2022-01-20 13:56:00,99.588875,99.588875,99.583612,100,100,100,100,100,100
2022-01-20 13:58:00,99.543177,99.543177,99.537907,100,100,100,100,100,100
2022-01-20 14:00:00,99.675963,99.675963,99.670726,100,100,100,100,100,100
2022-01-20 14:02:00,99.586367,99.586367,99.581100,100,100,100,100,100,100
2022-01-20 14:04:00,99.665204,99.665204,99.659997,100,100,100,100,100,100
2022-01-20 14:06:00,99.774311,99.774311,99.769210,100,100,100,100,100,100
2022-01-20 14:08:00,99.797949,99.797949,99.792989,100,100,100,100,100,100
2022-01-20 14:10:00,99.882886,99.882886,99.878190,100,100,100,100,100,100
2022-01-20 14:12:00,99.868678,99.868678,99.864446,100,100,100,100,100,100
2022-01-20 14:14:00,99.941878,99.941878,99.938666,100,100,100,100,100,100
2022-01-20 14:16:00,99.873034,99.873034,99.873034,100,100,100,100,100,100